env=dev
base.url=https://dev.yourapp.com
api.base.url=https://dev-api.yourapp.com
api.auth.token=dev-token-replace-me
browser=chrome
headless=false
platform=android
driver.mode=local
appium.server.url=http://localhost:4723
app.path=src/test/resources/apps/app-debug.apk
