env=prod
base.url=https://www.yourapp.com
api.base.url=https://api.yourapp.com
api.auth.token=prod-token-replace-me
browser=chrome
headless=true
platform=android
driver.mode=browserstack
browserstack.hub=https://hub-cloud.browserstack.com/wd/hub
browserstack.user=${BS_USER}
browserstack.key=${BS_KEY}
